namespace CodeClash.Courses.Domains.Courses;

public enum CodingTechnology
{
    Unspecified = 0,
    CSharp = 1,
    CPlusPlus = 2,
    Java = 3,
    JavaScript = 4,
    Kotlin = 5,
    Ruby = 6,
    Scala = 7,
    Rust = 8,
    C = 9,
    Golang = 10,
    FSharp = 11,
    VisualBasic = 12,
    Python = 13,
    TypeScript = 14,
    Lua = 15,
    Bash = 16,
    Shell = 17,
    Markdown = 18,
    Html = 19,
    Css = 20,
    Sql = 21,
    Swift = 22,
    Dart = 23,
    Php = 24,
    R = 25,
    Perl = 26,
    Haskell = 27,
    Elixir = 28,
    Clojure = 29,
    Erlang = 30,
    Zig = 31,
    Assembly = 32,
    ObjectiveC = 33,
    Groovy = 34,
    PowerShell = 35,
    Other = 36
}
